### ISSUE TITLE
Redo rebase

### ISSUE THREAD

**Issue by ramonaZmole** [IrinaDezmirean/EvozonInternship#4]
Create a new branch rebase2 from this point
![image](https://github.com/IrinaDezmirean/EvozonInternship/assets/12456781/d4a9a5a5-8c54-426c-baee-9eaff674fc4e)

Add a new file and push the changes 
Using rebase command update the rebase2 branch to get the latest changes from the main branch

**Comment by IrinaDezmirean** [comment]
Managed to rebase, please check if ok
