### ISSUE TITLE
Redo cherry pick 

### ISSUE THREAD

**Issue by ramonaZmole** [IrinaDezmirean/EvozonInternship#5]
create a new branch cherrypick2 from the main branch (make sure you have the latest changes on the main branch)
cherry-pick this commit 
![image](https://github.com/IrinaDezmirean/EvozonInternship/assets/12456781/a4f39631-8f3a-450f-ac48-47f4742818f7)
 on the cherrypick2 branch

**Comment by IrinaDezmirean** [comment]
Tried to redo it
